const fieldNotes={Tokyo:['35.6762° N, 139.6503° E','Neon. Ritual. Rhythm.','Take the city one neighbourhood at a time. Walk the quieter lanes before finding your way back to the energy of the main streets.'],Bali:['8.3405° S, 115.0920° E','Rain. Rice. Stillness.','Leave space between plans. The island’s terraces, small villages and coast invite a slower pace.'],Tuscany:['43.7711° N, 11.2486° E','Hills. Stone. Light.','A journey measured in hill towns and long lunches. Choose a base, then follow the smaller roads.'],Patagonia:['51.6230° S, 72.8550° W','Wind. Granite. Silence.','Open distances and changing weather shape every day here. Plan fewer stops, leave time for the trails, and keep your route flexible.'],Serengeti:['2.3333° S, 34.8333° E','Grass. Horizon. Wild.','Watch the landscape before looking for a sighting. A patient day, a local guide and a quiet departure change the experience.'],Santorini:['36.3932° N, 25.4615° E','White. Blue. Sea.','Walk before the midday crowds arrive. Beyond the familiar caldera views, the island rewards a little curiosity.'],Kyoto:['35.0116° N, 135.7681° E','Gardens. Craft. Time.','Move gently through temples and residential lanes. Let a garden, a tea room or a workshop become the centre of your day.'],'Machu Picchu':['13.1631° S, 72.5450° W','Cloud. Stone. Wonder.','The journey through the valley is part of the story. Allow time to acclimatise and plan entry arrangements ahead.'],Maldives:['3.2028° N, 73.2207° E','Water. Reef. Quiet.','A small island invites attention to small things: tide, shade and the life beneath the surface.']};
let activeJourney=null,chapter=0;let saved=[];try{saved=JSON.parse(localStorage.getItem('nomad_saved')||'[]');}catch{}
function renderDests(){document.getElementById('destGrid').innerHTML=(cf==='all'?destinations:destinations.filter(d=>d.region===cf)).map(d=>`<article class="dest-card"><img src="${d.img}&auto=format" alt="${d.name}" width="700" height="500" loading="lazy"><div class="dc-info"><div class="dc-loc">${d.loc} · ${fieldNotes[d.name][0]}</div><h3>${d.name}</h3><p>${fieldNotes[d.name][1]}</p><button class="dc-story" data-story="${d.name}" onclick="openJourney(this.dataset.story)">Read the field notes →</button></div></article>`).join('');}
function openJourney(name){activeJourney=destinations.find(d=>d.name===name);if(!activeJourney)return;chapter=0;renderChapter();document.getElementById('journeyReader').showModal();}
function renderChapter(){const d=activeJourney,n=fieldNotes[d.name];document.getElementById('readerImage').src=d.img.replace('w=700','w=1200');document.getElementById('readerImage').alt=d.name;document.getElementById('readerTitle').textContent=d.name;document.getElementById('readerLocation').textContent=n[0];document.getElementById('readerText').textContent=chapter===0?n[2]:`Start with a few days in ${d.name}. Leave room for unplanned walks and local recommendations. Add this destination to your personal trip draft and shape the details at your own pace.`;document.getElementById('readerChapter').textContent=`Field notes · ${chapter+1} / 2`;document.getElementById('nextChapter').textContent=chapter===0?'Planning notes →':'← Back to the story';document.getElementById('saveJourney').textContent=saved.includes(d.name)?'Saved to your journey ✓':'Save to my journey';}
function saveJourney(){if(!saved.includes(activeJourney.name))saved.push(activeJourney.name);try{localStorage.setItem('nomad_saved',JSON.stringify(saved));}catch{showToast('','Your browser could not save the journey.');return;}renderSaved();renderChapter();}
function renderSaved(){const host=document.getElementById('savedJourneys');host.replaceChildren();saved.forEach(name=>{const item=document.createElement('div');item.className='saved-journey';const title=document.createElement('span');title.textContent=name;const button=document.createElement('button');button.textContent='×';button.setAttribute('aria-label','Remove '+name);button.onclick=()=>{saved=saved.filter(x=>x!==name);localStorage.setItem('nomad_saved',JSON.stringify(saved));renderSaved();};item.append(title,button);host.append(item);});}
function submitPlan(){const name=document.getElementById('plName').value.trim(),email=document.getElementById('plEmail').value.trim();if(!name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){showToast('','Enter your name and a valid email.');return;}try{localStorage.setItem('nomad_plan',JSON.stringify({name,email,notes:document.getElementById('plNotes').value,destinations:saved,date:new Date().toISOString()}));showToast('','Trip draft saved in this browser. No inquiry was sent.');}catch{showToast('','Your browser could not save the draft. Your details remain in the form.');}}
document.getElementById('saveJourney').onclick=saveJourney;document.getElementById('nextChapter').onclick=()=>{chapter=1-chapter;renderChapter();};renderDests();renderSaved();
document.querySelectorAll('.form-group').forEach(group=>{const field=group.querySelector('input,select,textarea');const label=group.querySelector('label');if(field&&label)label.htmlFor=field.id;});
