const initialOrders=[['001','Sarah Johnson',85000,'delivered','2026-06-03'],['002','Ahmed Benali',245000,'delivered','2026-06-05'],['003','Leila Mansouri',205000,'shipped','2026-06-06'],['004','Mohamed Amine',210000,'shipped','2026-06-07'],['005','Yasmine Cherif',51000,'pending','2026-06-08'],['006','Rachid Kacem',490000,'delivered','2026-06-04'],['007','Karim Hadj',84000,'pending','2026-06-08'],['008','Nadia Boumediene',77000,'confirmed','2026-06-08']].map(([id,customer,total,status,date])=>({id:'ORD-2026-'+id,customer,total,status,date}));
let orders=read('admin_demo_orders',initialOrders),stock=read('admin_demo_products',[{id:1,name:'ProBook X1',category:'Tech',price:245000,stock:12},{id:2,name:'Silk Evening Dress',category:'Fashion',price:85000,stock:8},{id:3,name:'Wireless Earbuds Pro',category:'Tech',price:45000,stock:3},{id:4,name:'Cashmere Pullover',category:'Fashion',price:55000,stock:18},{id:5,name:'SmartWatch Ultra',category:'Tech',price:120000,stock:6},{id:6,name:'Leather Tote Bag',category:'Fashion',price:95000,stock:10}]);
let selected=new Set(),currentPage='dashboard',locale=read('admin_demo_lang','en');
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function persist(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{notify('Changes could not be saved in this browser.');}}
function money(value){return Number(value).toLocaleString('en-US')+' DZD';}
function escapeText(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function notify(text){const el=document.getElementById('toast');el.textContent=text;clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.textContent='',3500);}
function showPage(page){currentPage=page;document.querySelectorAll('.page').forEach(el=>el.classList.toggle('active',el.id==='page-'+page));document.querySelectorAll('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===page));document.getElementById('sidebar').classList.remove('open');document.getElementById('breadcrumbPage').textContent=page.charAt(0).toUpperCase()+page.slice(1);}
function setLang(value){locale=value;document.documentElement.lang=value;document.querySelectorAll('[data-en]').forEach(el=>el.textContent=el.dataset[value]);persist('admin_demo_lang',value);}
function toggleTheme(){const value=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=value;persist('admin_demo_theme',value);}
function filteredOrders(){const query=document.getElementById('orderSearch').value.toLowerCase(),status=document.getElementById('orderStatus').value,sort=document.getElementById('orderSort').value;return orders.filter(o=>(!status||o.status===status)&&(o.customer+' '+o.id).toLowerCase().includes(query)).sort((a,b)=>sort==='total'?b.total-a.total:sort==='customer'?a.customer.localeCompare(b.customer):b.date.localeCompare(a.date)||b.id.localeCompare(a.id));}
function orderRow(o,selectable=true){return `<tr>${selectable?`<td><input type="checkbox" aria-label="Select ${o.id}" ${selected.has(o.id)?'checked':''} onchange="selectOrder('${o.id}',this.checked)"></td>`:''}<td><strong>${o.id}</strong></td><td>${escapeText(o.customer)}</td><td>${o.date}</td><td><span class="status ${o.status}">${o.status}</span></td><td>${money(o.total)}</td>${selectable?`<td><select class="button" aria-label="Status for ${o.id}" onchange="updateStatus('${o.id}',this.value)">${['pending','confirmed','shipped','delivered'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></td>`:''}</tr>`;}
function renderOrders(){const list=filteredOrders();document.getElementById('orderRows').innerHTML=list.length?list.map(o=>orderRow(o)).join(''):'<tr><td colspan="7" class="empty">No orders match your search. Clear the search or change the status.</td></tr>';document.getElementById('orderCount').textContent=`${list.length} of ${orders.length} orders`;document.getElementById('selectAll').checked=list.length>0&&list.every(o=>selected.has(o.id));document.getElementById('bulkActions').hidden=!selected.size;document.getElementById('selectionCount').textContent=`${selected.size} selected`;}
function selectOrder(id,checked){checked?selected.add(id):selected.delete(id);renderOrders();}
function updateStatus(id,status){orders=orders.map(o=>o.id===id?{...o,status}:o);persist('admin_demo_orders',orders);renderAll();notify(id+' updated to '+status);}
function bulkUpdate(){const status=document.getElementById('bulkStatus').value;orders=orders.map(o=>selected.has(o.id)?{...o,status}:o);persist('admin_demo_orders',orders);notify(`${selected.size} orders updated to ${status}`);selected.clear();renderAll();}
function renderDashboard(){const total=orders.reduce((n,o)=>n+o.total,0),pending=orders.filter(o=>o.status==='pending'),customers=new Set(orders.map(o=>o.customer)).size;document.getElementById('statRevenue').textContent=money(total);document.getElementById('statOrders').textContent=orders.length;document.getElementById('statPending').textContent=pending.length;document.getElementById('statAverage').textContent=money(total/Math.max(orders.length,1));document.getElementById('attentionRows').innerHTML=pending.length?pending.map(o=>orderRow(o,false)).join(''):'<tr><td colspan="5" class="empty">No pending orders. Your queue is clear.</td></tr>';const dates=[...new Set(orders.map(o=>o.date))].sort();const daily=dates.map(date=>({date,value:orders.filter(o=>o.date===date).reduce((n,o)=>n+o.total,0)}));const max=Math.max(...daily.map(d=>d.value),1);document.getElementById('revenueBars').innerHTML=daily.map(d=>`<div class="bar-col" style="--height:${d.value/max*80}%"><div class="bar" style="height:${d.value/max*80}%" aria-label="${d.date}: ${money(d.value)}"></div><span>${Math.round(d.value/1000)}k</span><small>${d.date.slice(5)}</small></div>`).join('');document.getElementById('analyticsSummary').innerHTML=`<div><small>Order value in sample</small><strong>${money(total)}</strong></div><div><small>Customers in sample</small><strong>${customers}</strong></div><div><small>Awaiting confirmation</small><strong>${pending.length}</strong></div>`;}
function renderProducts(){const query=document.getElementById('productSearch').value.toLowerCase();const list=stock.filter(p=>(p.name+' '+p.category).toLowerCase().includes(query));document.getElementById('productRows').innerHTML=list.length?list.map(p=>`<tr><td><strong>${escapeText(p.name)}</strong><small>SKU ${String(p.id).padStart(4,'0')}</small></td><td>${escapeText(p.category)}</td><td>${money(p.price)}</td><td><span class="status ${p.stock<5?'pending':'delivered'}">${p.stock} available</span></td><td><button class="button" onclick="editProduct(${p.id})">Edit</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">No products match your search.</td></tr>';}
function renderCustomers(){const query=document.getElementById('customerSearch').value.toLowerCase();const names=[...new Set(orders.map(o=>o.customer))].filter(n=>n.toLowerCase().includes(query));document.getElementById('customerRows').innerHTML=names.length?names.map(name=>{const list=orders.filter(o=>o.customer===name);return `<tr><td>${escapeText(name)}</td><td>${list.length}</td><td>${money(list.reduce((n,o)=>n+o.total,0))}</td><td>${list.map(o=>o.date).sort().at(-1)}</td></tr>`;}).join(''):'<tr><td colspan="4" class="empty">No customers match your search.</td></tr>';}
function renderAll(){renderOrders();renderDashboard();renderProducts();renderCustomers();}
function openCommand(){document.getElementById('commandDialog').showModal();document.getElementById('commandInput').value='';renderCommand();document.getElementById('commandInput').focus();}
function renderCommand(){const query=document.getElementById('commandInput').value.toLowerCase();const routes=['dashboard','orders','products','customers','analytics','settings'].filter(x=>x.includes(query));let html=routes.map(route=>`<button class="command-result" onclick="showPage('${route}');document.getElementById('commandDialog').close()"><span>Go to ${route}</span><small>Page →</small></button>`).join('');if(query)html+=orders.filter(o=>(o.id+' '+o.customer).toLowerCase().includes(query)).map(o=>`<button class="command-result" onclick="openOrderFromCommand('${o.id}')"><span>${o.id} · ${escapeText(o.customer)}</span><small>${o.status}</small></button>`).join('');document.getElementById('commandResults').innerHTML=html||'<p class="empty">No results. Try a customer name, order ID or page.</p>';}
function openOrderFromCommand(id){showPage('orders');document.getElementById('orderSearch').value=id;document.getElementById('orderStatus').value='';renderOrders();document.getElementById('commandDialog').close();}
function exportCSV(){const list=filteredOrders();const quote=value=>'"'+String(value).replaceAll('"','""')+'"';const csv=[['Order','Customer','Date','Status','Total DZD'],...list.map(o=>[o.id,o.customer,o.date,o.status,o.total])].map(row=>row.map(quote).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='admin-orders.csv';a.click();URL.revokeObjectURL(url);notify('Exported '+list.length+' orders.');}
function editProduct(id){const p=stock.find(p=>p.id===id);document.getElementById('productId').value=p?.id||'';for(const key of ['name','price','stock','category'])document.getElementById('product-'+key).value=p?.[key]??(key==='category'?'Tech':'');document.getElementById('productDialog').showModal();}
function saveProduct(event){event.preventDefault();const id=Number(document.getElementById('productId').value)||Date.now();const p={id,name:document.getElementById('product-name').value.trim(),category:document.getElementById('product-category').value,price:Number(document.getElementById('product-price').value),stock:Number(document.getElementById('product-stock').value)};if(!p.name||p.price<0||p.stock<0)return;stock=stock.some(x=>x.id===id)?stock.map(x=>x.id===id?p:x):[...stock,p];persist('admin_demo_products',stock);renderProducts();document.getElementById('productDialog').close();notify('Product saved.');}
document.querySelectorAll('[data-page]').forEach(el=>el.onclick=()=>showPage(el.dataset.page));for(const id of ['orderSearch','orderStatus','orderSort'])document.getElementById(id).addEventListener(id==='orderSearch'?'input':'change',renderOrders);document.getElementById('selectAll').onchange=e=>{filteredOrders().forEach(o=>e.target.checked?selected.add(o.id):selected.delete(o.id));renderOrders();};document.getElementById('productSearch').oninput=renderProducts;document.getElementById('customerSearch').oninput=renderCustomers;document.getElementById('commandInput').oninput=renderCommand;document.getElementById('productForm').onsubmit=saveProduct;document.getElementById('settingsForm').onsubmit=e=>{e.preventDefault();persist('admin_demo_settings',{name:document.getElementById('workspaceName').value,currency:'DZD'});notify('Workspace settings saved.');};document.getElementById('workspaceName').value=read('admin_demo_settings',{name:'Playground store'}).name;
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand();}if(e.key==='Escape')document.getElementById('sidebar').classList.remove('open');if(e.key==='ArrowDown'&&document.getElementById('commandDialog').open){e.preventDefault();const buttons=[...document.querySelectorAll('.command-result')];buttons[(buttons.indexOf(document.activeElement)+1)%buttons.length]?.focus();}});
document.documentElement.dataset.theme=read('admin_demo_theme','light');setLang(locale);renderAll();
