import assert from "node:assert/strict";
import { chromium, expect } from "@playwright/test";

const browser = await chromium.launch({ channel: "chrome", headless: true });
const url = process.env.TEST_URL || "http://127.0.0.1:5174/zenimyoucef/";
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: "no-preference" });
  await page.clock.install();
  await page.goto(url, { waitUntil: "networkidle" });
  const live = page.locator("#live-gallery");
  await live.scrollIntoViewIfNeeded();
  await page.mouse.move(1, 1);
  await expect(live).toHaveAttribute("data-autoplay", "running");
  await page.clock.runFor(4900);
  await expect(live.locator(".gallery-progress")).toHaveText("01 / 03");
  await page.clock.runFor(1100);
  await expect(live.locator(".gallery-progress")).toHaveText("02 / 03");
  await page.clock.runFor(6000);
  await expect(live.locator(".gallery-progress")).toHaveText("03 / 03");
  await page.clock.runFor(6000);
  await expect(live.locator(".gallery-progress")).toHaveText("01 / 03");
  const focusedBefore = await page.evaluate(() => document.activeElement.tagName);
  await page.evaluate(() => {
    Object.defineProperty(document, "hidden", { configurable: true, get: () => window.testTabHidden });
    window.testTabHidden = true;
    document.dispatchEvent(new Event("visibilitychange"));
  });
  await expect(live).toHaveAttribute("data-autoplay", "paused");
  await page.clock.runFor(7000);
  await expect(live.locator(".gallery-progress")).toHaveText("01 / 03");
  await page.evaluate(() => { window.testTabHidden = false; document.dispatchEvent(new Event("visibilitychange")); });
  await expect(live).toHaveAttribute("data-autoplay", "running");
  await page.clock.runFor(4900);
  await expect(live.locator(".gallery-progress")).toHaveText("01 / 03");
  assert.equal(await page.evaluate(() => document.activeElement.tagName), focusedBefore, "Automatic advance never moves focus");
  await live.hover();
  await expect(live).toHaveAttribute("data-autoplay", "paused");
  await page.clock.runFor(7000);
  await expect(live.locator(".gallery-progress")).toHaveText("01 / 03");
  await live.getByRole("button", { name: "Show TKI TEC" }).click();
  await page.clock.runFor(1000);
  await expect(live.locator(".gallery-progress")).toHaveText("02 / 03");
  await page.mouse.move(1, 1);
  await expect(live).toHaveAttribute("data-autoplay", "paused");
  await page.clock.runFor(6000);
  await expect(live.locator(".gallery-progress")).toHaveText("02 / 03");
  await page.locator(".brand").first().evaluate(el => el.focus({ preventScroll: true }));
  await expect(live).toHaveAttribute("data-autoplay", "running");
  await page.clock.runFor(4900);
  await expect(live.locator(".gallery-progress")).toHaveText("02 / 03");
  await page.clock.runFor(1100);
  await expect(live.locator(".gallery-progress")).toHaveText("03 / 03");
  await live.getByRole("button", { name: "Pause automatic advance" }).click();
  await page.locator(".brand").first().evaluate(el => el.focus({ preventScroll: true }));
  await page.mouse.move(1, 1);
  await page.clock.runFor(7000);
  await expect(live.locator(".gallery-progress")).toHaveText("03 / 03");
  await live.getByRole("button", { name: "Resume automatic advance" }).click();
  await page.locator(".brand").first().evaluate(el => el.focus({ preventScroll: true }));
  await page.mouse.move(1, 1);
  await expect(live).toHaveAttribute("data-autoplay", "running");
  await page.emulateMedia({ reducedMotion: "reduce" });
  await expect(live).toHaveAttribute("data-autoplay", "paused");
  await page.clock.runFor(7000);
  await expect(live.locator(".gallery-progress")).toHaveText("03 / 03");
  await live.getByRole("button", { name: "Previous live project" }).click();
  await expect(live.locator(".gallery-progress")).toHaveText("02 / 03");
  const archive = page.locator("#playground-gallery");
  await archive.scrollIntoViewIfNeeded();
  await page.emulateMedia({ reducedMotion: "no-preference" });
  await page.locator(".brand").first().evaluate(el => el.focus({ preventScroll: true }));
  await page.mouse.move(1, 1);
  await expect(archive).toHaveAttribute("data-autoplay", "running");
  const before = await archive.locator(".gallery-track").evaluate(el => el.scrollLeft);
  await page.clock.runFor(6000);
  assert.ok(await archive.locator(".gallery-track").evaluate(el => el.scrollLeft) > before + 20, "Playground automatically advances too");
  await expect(live).toHaveAttribute("data-autoplay", "paused");
  await archive.locator(".gallery-track").focus();
  await page.keyboard.press("End");
  await page.clock.runFor(1000);
  await page.locator(".brand").first().evaluate(el => el.focus({ preventScroll: true }));
  await page.mouse.move(1, 1);
  await page.clock.runFor(6500);
  await expect(archive.locator(".gallery-progress")).toHaveText("01 / 09");

  const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: "no-preference" });
  const mobile = await mobileContext.newPage();
  await mobile.clock.install();
  await mobile.goto(url, { waitUntil: "networkidle" });
  const mobileGallery = mobile.locator("#live-gallery");
  const mobileTrack = mobileGallery.locator(".gallery-track");
  await mobileTrack.scrollIntoViewIfNeeded();
  await expect(mobileGallery).toHaveAttribute("data-autoplay", "running");
  const box = await mobileTrack.boundingBox();
  const cdp = await mobileContext.newCDPSession(mobile);
  const x = box.x + box.width * .85;
  const y = Math.max(100, box.y + 140);
  await cdp.send("Input.dispatchTouchEvent", { type: "touchStart", touchPoints: [{ x, y }] });
  await expect(mobileGallery).toHaveAttribute("data-autoplay", "paused");
  await mobile.clock.runFor(7000);
  await expect(mobileGallery.locator(".gallery-progress")).toHaveText("01 / 03");
  for (let i = 1; i <= 12; i++) {
    await cdp.send("Input.dispatchTouchEvent", { type: "touchMove", touchPoints: [{ x: x - i * 23, y }] });
    await mobile.clock.runFor(20);
  }
  await cdp.send("Input.dispatchTouchEvent", { type: "touchEnd", touchPoints: [] });
  await mobile.clock.runFor(1200);
  await expect(mobileGallery.locator(".gallery-progress")).toHaveText("02 / 03");
  await expect(mobileGallery).toHaveAttribute("data-autoplay", "running");
  await mobile.clock.runFor(6500);
  await expect(mobileGallery.locator(".gallery-progress")).toHaveText("03 / 03");
  await mobileContext.close();
  console.log("PASS: five-second autoplay, both loops, hover/focus/user/hidden-tab pause, timer reset, reduced motion, direct selection and native touch pause/resume.");
} finally {
  await browser.close();
}
