/* Presentation-only enhancement. Prices, product IDs and cart/order contracts stay in index.html. */
const icons={search:'<circle cx="10.5" cy="10.5" r="7.5"/><path d="m16 16 5 5"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',cart:'<path d="M2 3h3l3 13h11l3-10H6"/><circle cx="9" cy="21" r="1"/><circle cx="19" cy="21" r="1"/>',user:'<circle cx="12" cy="7" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3Z"/>',menu:'<path d="M3 5h18M3 12h18M3 19h18"/>',truck:'<path d="M1 5h13v12H1M14 9h4l4 5v3h-8M3 2h7M1 9h5"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="18" r="3"/>',shield:'<path d="m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6Z"/><path d="m8 12 3 3 5-6"/>',badge:'<path d="m12 2 3 2 4 1 1 4 2 3-2 3-1 4-4 1-3 2-3-2-4-1-1-4-2-3 2-3 1-4 4-1Z"/><path d="m8 12 3 3 5-6"/>',headphones:'<path d="M3 14v-3a9 9 0 0 1 18 0v3M5 12H3v8h4v-8ZM19 12h2v8h-4v-8ZM21 19v2l-5 1"/>',graduate:'<path d="m1 7 11-5 11 5-11 5ZM5 10v7c4 3 10 3 14 0v-7M23 7v9"/>',settings:'<path d="m9 2-1 3-3 1-3 4 2 2-2 3 3 4 3 1 1 3h6l1-3 3-1 3-4-2-3 2-2-3-4-3-1-1-3Z"/><circle cx="12" cy="12" r="4"/>',gamepad:'<path d="M7 6h10c4 0 6 12 4 14-2 2-5-4-6-4H9c-1 0-4 6-6 4C1 18 3 6 7 6Z"/><path d="M6 10v5M3.5 12.5h5"/><circle cx="16" cy="10" r=".5"/><circle cx="19" cy="13" r=".5"/>'};
function icon(name){return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.settings}</svg>`;}
function hydrateIcons(){document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));}
let wishlist;try{wishlist=new Set(JSON.parse(localStorage.getItem('qn_wishlist')||'[]').filter(id=>products.some(p=>p.id===id)));}catch{wishlist=new Set();}
let catalogQuery='',favoritesOnly=false;
const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toggleWishlist(id){if(wishlist.has(id))wishlist.delete(id);else wishlist.add(id);localStorage.setItem('qn_wishlist',JSON.stringify([...wishlist]));renderProducts();updateWishlistBadge();}
function updateWishlistBadge(){const badge=document.getElementById('wishlistBadge');badge.textContent=wishlist.size;badge.classList.toggle('show',wishlist.size>0);}
function showWishlist(){favoritesOnly=true;catalogQuery='';tab='all';document.getElementById('productSearch').value='';syncTabs();renderProducts();document.getElementById('products').scrollIntoView({behavior:'smooth'});}
function syncTabs(){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));}
function selectCategory(category){tab=category;catalogQuery='';favoritesOnly=false;document.getElementById('productSearch').value='';syncTabs();renderProducts();}
function quickSearch(category){if(['laptops','phones','audio'].includes(category))selectCategory(category);else{tab='all';favoritesOnly=false;catalogQuery=category;document.getElementById('productSearch').value=category;syncTabs();renderProducts();}document.getElementById('products').scrollIntoView({behavior:'smooth'});}
function clearCatalog(){selectCategory('all');}
function focusSearch(){document.getElementById('showroomTitle').scrollIntoView({behavior:'smooth',block:'center'});document.getElementById('productSearch').focus({preventScroll:true});}
function searchProducts(event){event.preventDefault();catalogQuery=document.getElementById('productSearch').value.trim().toLocaleLowerCase('fr');favoritesOnly=false;tab='all';syncTabs();renderProducts();document.getElementById('products').scrollIntoView({behavior:'smooth'});}
function renderProducts(){
 const aliases={laptops:'macbook pc portable ordinateur',phones:'iphone smartphone téléphone',audio:'casque headphones écouteurs audio'};
 const list=products.filter(p=>(tab==='all'||p.tab===tab)&&(!favoritesOnly||wishlist.has(p.id))&&(!catalogQuery||`${p.name} ${p.specs.join(' ')} ${aliases[p.tab]}`.toLocaleLowerCase('fr').includes(catalogQuery)));
 document.getElementById('catalogStatus').textContent=favoritesOnly?`Mes favoris · ${list.length} produit${list.length>1?'s':''}`:catalogQuery?`${list.length} résultat${list.length>1?'s':''} pour « ${catalogQuery} »`:'';
 document.getElementById('productGrid').innerHTML=list.length?list.map(p=>`<article class="product-card"><div class="pc-img"><img src="${p.img}" alt="${escapeHTML(p.name)}" loading="lazy" width="600" height="400">${p.tag?`<span class="pc-tag ${p.tag}">${p.tag==='new'?'NOUVEAU':'BEST SELLER'}</span>`:''}<button class="wishlist-button" onclick="toggleWishlist(${p.id})" aria-label="${wishlist.has(p.id)?'Retirer':'Ajouter'} ${escapeHTML(p.name)} ${wishlist.has(p.id)?'des':'aux'} favoris" aria-pressed="${wishlist.has(p.id)}">${icon('heart')}</button></div><div class="pc-body"><h3><button class="pc-title-button" onclick="openDetail(${p.id})">${escapeHTML(p.name)}</button></h3><p class="pc-specs">${escapeHTML(p.specs.join(' · '))}</p><div class="pc-bottom"><span class="pc-price">${fmtDZD(p.price)}</span><button class="pc-buy" onclick="addToCart(${p.id})" aria-label="Ajouter ${escapeHTML(p.name)} au panier">${icon('cart')}<span class="add-label">Ajouter au panier</span></button></div><label class="compare-check"><input type="checkbox" data-compare="${p.id}" ${compared.has(p.id)?'checked':''} onchange="toggleCompare(${p.id},this)">Comparer</label></div></article>`).join(''):`<div class="empty-products"><h3>${favoritesOnly?'Votre sélection commence ici.':'Aucun produit trouvé.'}</h3><p>${favoritesOnly?'Touchez le cœur d’un produit pour le retrouver dans vos favoris.':'Essayez un autre mot-clé ou explorez notre catalogue.'}</p><button onclick="clearCatalog()">Voir tous les produits</button></div>`;
}
/* The existing detail action remains the cart entry point; direct ordering keeps its existing contract. */
function openDetail(id){const p=products.find(x=>x.id===id);if(!p)return;document.getElementById('modalContent').innerHTML=`<img class="detail-photo" src="${p.img}" alt="${escapeHTML(p.name)}"><h2>${escapeHTML(p.name)}</h2><p class="pc-price">${fmtDZD(p.price)}</p><p class="detail-specs">${escapeHTML(p.specs.join(' · '))}</p><div class="detail-actions"><button class="btn btn-accent" onclick="addToCart(${p.id});document.getElementById('checkoutModal').classList.remove('open')">Ajouter au panier</button>${p.stock?`<button class="btn btn-ghost" onclick="document.getElementById('checkoutModal').classList.remove('open');openBuyNow(${p.id})">Commander maintenant</button>`:''}</div>`;document.getElementById('checkoutModal').classList.add('open');document.querySelector('#checkoutModal button').focus();}
/* Existing pages initialize stock/orders through their current hooks; no stock is invented. */
if(!document.getElementById('buynowOverlay')){const overlay=document.createElement('div');overlay.id='buynowOverlay';overlay.innerHTML='<div id="buynowModal" role="dialog" aria-modal="true" aria-label="Commander un produit"></div>';overlay.addEventListener('click',e=>{if(e.target===overlay)overlay.classList.remove('open');});document.body.append(overlay);}
document.getElementById('checkoutModal').setAttribute('role','dialog');document.getElementById('checkoutModal').setAttribute('aria-modal','true');document.getElementById('checkoutModal').setAttribute('aria-label','Détails du produit');
document.querySelector('#checkoutModal .modal>button').setAttribute('aria-label','Fermer les détails');
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.getElementById('buynowOverlay').classList.remove('open');document.getElementById('menuToggle').setAttribute('aria-expanded','false');}if(e.key==='Tab'){const modal=document.querySelector('#checkoutModal.open .modal, #buynowOverlay.open #buynowModal, #cartSidebar.open');if(!modal)return;const focusable=[...modal.querySelectorAll('button,a[href],input,select,textarea')].filter(el=>el.getClientRects().length);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
document.getElementById('menuToggle').addEventListener('click',()=>document.getElementById('menuToggle').setAttribute('aria-expanded',document.getElementById('nav').classList.contains('open')));
document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{catalogQuery='';favoritesOnly=false;document.getElementById('productSearch').value='';renderProducts();}));
hydrateIcons();renderProducts();updateWishlistBadge();
